import type { SessionRecord } from "../memory/sessionMemory.js";
import { buildReviewCommentDrafts, renderReviewCommentDrafts } from "../review/commentExport.js";

export function renderGithubPrReport(session: SessionRecord): string {
  const state = session.state;
  const selected = state.candidates.find((candidate) => candidate.candidateId === state.judge?.selectedCandidateId) ?? state.candidates[0];
  const shellLines = state.runResults.length
    ? state.runResults.map((result) => `- \`${result.command}\`: exit=${result.exitCode ?? "unknown"}, success=${result.success ?? "unknown"}`).join("\n")
    : "- No shell commands recorded.";
  const patchLines = state.candidates.length
    ? state.candidates.slice(0, 5).map((candidate) => `- ${candidate.candidateId}: ${candidate.summary} (${candidate.filesChanged.join(", ") || "no files"})`).join("\n")
    : "- No patch candidates recorded.";
  const reviewDrafts = buildReviewCommentDrafts(session, "github");
  const reviewBody = renderReviewCommentDrafts(reviewDrafts, "github");

  return [
    "## TomorrowEdge Report",
    "",
    `Session: \`${session.sessionId}\``,
    `Goal: ${state.goal}`,
    `Result: ${state.finalSummary?.result ?? "unknown"}`,
    `Access: ${state.access.mode}`,
    `Trace events: ${state.events.length}`,
    state.traceCompleteness ? `Trace completeness: ${state.traceCompleteness.score}/100` : "Trace completeness: n/a",
    selected ? `Selected candidate: \`${selected.candidateId}\`` : "Selected candidate: none",
    "",
    "### Routing",
    state.routing.assignments
      .filter((assignment) => ["planner", "coder_a", "reviewer", "judge", "runner"].includes(assignment.role))
      .map((assignment) => `- ${assignment.role}: ${assignment.provider}/${assignment.model}`)
      .join("\n") || "- No routing assignments recorded.",
    "",
    "### Patch Candidates",
    patchLines,
    "",
    "### Shell Checks",
    shellLines,
    "",
    "### Review Drafts",
    reviewBody,
    "",
    "Generated by TomorrowEdge."
  ].join("\n");
}
