import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { TomorrowEdgeConfig } from "../../config/schema.js";
import { runAgentCouncilGovernance, type CouncilRunOptions } from "../council/councilRuntime.js";
import type { ObjectiveContractV1 } from "../contracts/objectiveContract.js";
import { runApprovedCommand } from "../tools/shellTool.js";
import type { DesiredStateDiff, GoalSpec, ObservedWorkspaceState, StatusSpec } from "./specs.js";

export type ControlPlaneActionInput = {
  cwd: string;
  goal: GoalSpec;
  iteration: number;
  observed: ObservedWorkspaceState;
  delta: DesiredStateDiff;
  status?: StatusSpec;
  evidenceDir: string;
};

export type ControlPlaneActionResult = {
  status: "success" | "failed" | "skipped";
  summary: string;
  changedFiles: string[];
  commandsRun: string[];
  artifacts: Array<Record<string, unknown>>;
  error?: string;
  budgetExhausted?: boolean;
};

export interface ControlPlaneAgentAdapter {
  id: string;
  act(input: ControlPlaneActionInput): Promise<ControlPlaneActionResult>;
}

export class NoopAgentAdapter implements ControlPlaneAgentAdapter {
  readonly id = "noop";

  async act(): Promise<ControlPlaneActionResult> {
    return {
      status: "skipped",
      summary: "Noop adapter made no changes.",
      changedFiles: [],
      commandsRun: [],
      artifacts: []
    };
  }
}

export class MockAgentAdapter implements ControlPlaneAgentAdapter {
  readonly id = "mock";

  async act(input: ControlPlaneActionInput): Promise<ControlPlaneActionResult> {
    const target = chooseMockWriteTarget(input.goal);
    if (!target) {
      return {
        status: "skipped",
        summary: "Mock adapter found no structured artifact or diff target to create.",
        changedFiles: [],
        commandsRun: [],
        artifacts: []
      };
    }
    const absolute = path.resolve(input.cwd, target);
    await mkdir(path.dirname(absolute), { recursive: true });
    const content = [
      `# ${input.goal.title}`,
      "",
      `Generated by TomorrowEdge Canopus mock AgentBridge.`,
      `Iteration: ${input.iteration}`,
      `Goal: ${input.goal.description}`,
      "",
      `Missing conditions before action: ${input.delta.missing_conditions.join(", ") || "none"}`,
      ""
    ].join("\n");
    await writeFile(absolute, content, "utf8");
    return {
      status: "success",
      summary: `Mock adapter wrote ${target}.`,
      changedFiles: [target.replace(/\\/g, "/")],
      commandsRun: [],
      artifacts: [{ path: target, kind: "file", description: "mock AgentBridge output" }]
    };
  }
}

export class ShellAgentAdapter implements ControlPlaneAgentAdapter {
  readonly id = "shell";

  constructor(private readonly command: string, private readonly timeoutMs = 60_000) {}

  async act(input: ControlPlaneActionInput): Promise<ControlPlaneActionResult> {
    const result = await runShell(this.command, input.cwd, this.timeoutMs);
    const logPath = path.join(input.evidenceDir, "actuator_shell.log");
    await mkdir(input.evidenceDir, { recursive: true });
    await writeFile(logPath, [
      `$ ${this.command}`,
      `exit_code=${result.exitCode}`,
      "",
      "# stdout",
      result.stdout,
      "",
      "# stderr",
      result.stderr
    ].join("\n"), "utf8");
    return {
      status: result.exitCode === 0 ? "success" : "failed",
      summary: result.exitCode === 0 ? "Shell adapter command succeeded." : `Shell adapter command failed with exit code ${result.exitCode}.`,
      changedFiles: [],
      commandsRun: [this.command],
      artifacts: [{ path: logPath, kind: "log", description: "shell AgentBridge output" }],
      error: result.exitCode === 0 ? undefined : result.error ?? `exit code ${result.exitCode}`
    };
  }
}

export type SiriusCouncilActuatorOptions = Pick<CouncilRunOptions, "accessMode" | "fixtureMode" | "approvePatch" | "approveShell" | "simulateFailureTaskId" | "maxMutations">;

export class SiriusCouncilActuatorAdapter implements ControlPlaneAgentAdapter {
  readonly id = "sirius-council";

  constructor(private readonly config: TomorrowEdgeConfig, private readonly options: SiriusCouncilActuatorOptions = {}) {}

  async act(input: ControlPlaneActionInput): Promise<ControlPlaneActionResult> {
    await mkdir(input.evidenceDir, { recursive: true });
    try {
      const state = await runAgentCouncilGovernance(input.cwd, buildCouncilGoal(input), this.config, {
        accessMode: this.options.accessMode,
        fixtureMode: this.options.fixtureMode,
        approvePatch: this.options.approvePatch,
        approveShell: this.options.approveShell,
        simulateFailureTaskId: this.options.simulateFailureTaskId,
        maxMutations: this.options.maxMutations
      });
      const actionPath = path.join(input.evidenceDir, "sirius_council_action.json");
      const eventsPath = path.join(input.evidenceDir, "sirius_council_events.jsonl");
      await writeFile(actionPath, JSON.stringify({
        sessionId: state.sessionId,
        chiefAgent: state.chiefAgent,
        chiefDecision: state.chiefDecision,
        councilStatus: state.council?.status,
        taskGraph: state.plan?.taskGraph,
        delegatedTaskResults: state.delegatedTaskResults,
        strategyMutations: state.strategyMutations,
        finalChiefReview: state.finalChiefReview,
        traceCompleteness: state.traceCompleteness,
        summary: state.finalSummary
      }, null, 2), "utf8");
      await writeFile(eventsPath, state.events.map((event) => JSON.stringify(event)).join("\n") + "\n", "utf8");
      const completed = state.finalChiefReview?.decision === "approve_delivery" || state.finalSummary?.result === "completed";
      return {
        status: completed ? "success" : "failed",
        summary: completed
          ? `Sirius Council AgentBridge completed session ${state.sessionId}.`
          : `Sirius Council AgentBridge completed session ${state.sessionId} without delivery approval.`,
        changedFiles: state.changedFiles ?? [],
        commandsRun: (state.runResults ?? []).map((result) => result.command),
        artifacts: [
          { path: actionPath, kind: "json", description: "Sirius Council AgentBridge result" },
          { path: eventsPath, kind: "jsonl", description: "Sirius Council event ledger" }
        ],
        error: completed ? undefined : state.finalChiefReview?.unresolvedRisks?.join("; ") || state.finalSummary?.risksRemaining?.join("; ")
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const errorPath = path.join(input.evidenceDir, "sirius_council_error.json");
      await writeFile(errorPath, JSON.stringify({
        adapter: this.id,
        status: "failed",
        error: message
      }, null, 2), "utf8");
      return {
        status: "failed",
        summary: `Sirius Council AgentBridge failed: ${message}`,
        changedFiles: [],
        commandsRun: [],
        artifacts: [{ path: errorPath, kind: "json", description: "Sirius Council AgentBridge error" }],
        error: message
      };
    }
  }
}

export function objectiveContractToGoalSpec(contract: ObjectiveContractV1): GoalSpec {
  return {
    id: contract.contractId,
    title: contract.localObjective || contract.goal,
    description: contract.normalizedGoal || contract.goal,
    mode: mapScenarioToGoalMode(contract.scenarioType),
    desired_state: {
      summary: contract.stopCondition.success.join(" | ") || contract.localObjective,
      success_conditions: contract.successCriteria.map((criterion, index) => ({
        id: `contract_success_${index + 1}`,
        description: criterion,
        type: contract.verificationRubric.requiredCommands.length > 0 ? "test" : "manual",
        required: true
      }))
    },
    constraints: {
      allowed_paths: ["."],
      denied_paths: [".git", ".runs"],
      max_files_changed: null,
      max_iterations: contract.budget.maxSteps,
      require_human_review: contract.riskLevel === "high"
    },
    artifacts: {
      required: contract.verificationRubric.requiredArtifacts.map((artifact) => ({
        path: artifact,
        description: "Objective Contract required artifact"
      }))
    }
  };
}

function chooseMockWriteTarget(goal: GoalSpec): string | null {
  const artifact = goal.artifacts.required[0]?.path;
  if (artifact) return artifact;
  const fileCondition = goal.desired_state.success_conditions.find((item) => item.type === "file_exists" && item.path);
  if (fileCondition?.path) return fileCondition.path;
  if (goal.desired_state.success_conditions.some((item) => item.type === "diff_required")) return "control-plane-output.txt";
  return null;
}

function mapScenarioToGoalMode(scenario: string): GoalSpec["mode"] {
  if (scenario === "research") return "research";
  if (scenario === "document") return "docs";
  if (scenario === "debugging") return "coding";
  if (scenario === "refactor") return "refactor";
  if (scenario === "analysis") return "generic";
  return "coding";
}

function buildCouncilGoal(input: ControlPlaneActionInput): string {
  const missing = input.delta.missing_conditions.join(", ") || "none";
  const satisfied = input.delta.satisfied_conditions.join(", ") || "none";
  const changed = input.observed.files_changed.join(", ") || "none";
  return [
    input.goal.description,
    "",
    "Canopus AgentBridge task:",
    `- ObjectiveContract: ${input.goal.id} / ${input.goal.title}`,
    `- Desired state: ${input.goal.desired_state.summary}`,
    `- Missing success conditions: ${missing}`,
    `- Satisfied success conditions: ${satisfied}`,
    `- Currently changed files: ${changed}`,
    `- Iteration: ${input.iteration}`,
    "",
    "Act only within the objective constraints. Canopus blocking checks remain authoritative after this action."
  ].join("\n");
}

async function runShell(command: string, cwd: string, timeoutMs: number): Promise<{ exitCode: number; stdout: string; stderr: string; error?: string }> {
  try {
    const result = await runApprovedCommand(cwd, command, {
      approved: true,
      policy: "verification_allowlist",
      timeoutMs
    });
    return {
      exitCode: result.exitCode,
      stdout: result.stdout,
      stderr: result.stderr
    };
  } catch (error) {
    return {
      exitCode: 1,
      stdout: "",
      stderr: "",
      error: error instanceof Error ? error.message : String(error)
    };
  }
}
