import type { ContextSelection } from "../context/fileSelector.js";
import type { AgentRunState } from "../../schemas/agentTask.js";
import type { FinalSummary, RunResult } from "../../schemas/evidence.js";
import type { DebateRound, DebateSession } from "../../schemas/debate.js";
import type { JudgeDecision } from "../../schemas/judge.js";
import type { ModelBudgetStatus, ModelNote, ModelUsageSummary } from "../../schemas/modelNote.js";
import type { PatchCandidate } from "../../schemas/patchCandidate.js";
import type { Plan } from "../../schemas/plan.js";
import type { ReviewReport } from "../../schemas/review.js";
import type { CapabilityRoute } from "../../schemas/capabilityRoute.js";
import type { StructuredVisualSpec } from "../../schemas/visualSpec.js";
import type { RoutingPlan } from "../routing/policies.js";
import type { AccessPolicy } from "../permissions/accessPolicy.js";
import type { EventArtifact, TomorrowEdgeEvent } from "../events/eventTypes.js";
import type { ConversationTarget } from "../../schemas/conversation.js";
import type { EvidencePacket } from "../evidence/evidencePacket.js";
import type { ProviderView } from "../contextProjection/providerView.js";
import type { TraceCompleteness } from "../diagnostics/traceCompleteness.js";
import type { BudgetRuntimeState } from "../budget/budgetGate.js";
import type { RoleGraph } from "../orchestration/roleGraph.js";
import type { RoleGraphExecutionState } from "../orchestration/roleGraphScheduler.js";
import type { WorkflowKind } from "../orchestration/workflowKind.js";
import type { TaskGovernanceDecision } from "../goal/taskGovernance.js";
import type { FailureMemoryInfluenceState } from "../memory/failureMemoryInfluence.js";
import type { ScenarioProfile } from "../scenarios/scenarioTypes.js";
import type { ObjectiveContractV1, ContractVerificationResult } from "../contracts/objectiveContract.js";
import type { ObjectiveTraceV1 } from "../traces/objectiveTrace.js";
import type { OrchestrationPolicyGenome } from "../orchestrationPolicy/orchestrationPolicy.js";
import type { ToolSkillRouteDecision } from "../skills/toolSkillRouter.js";
import type { ChiefAgentDecision, ChiefAgentProfile } from "../chiefAgent/chiefAgentTypes.js";
import type { FinalChiefReview } from "../chiefAgent/finalChiefReview.js";
import type { CouncilSession } from "../council/councilTypes.js";
import type { DelegatedTaskResult } from "../delegatedExecution/delegatedExecutionTypes.js";
import type { StrategyGenome } from "../evolution/strategyGenome.js";
import type { StrategyMutationEvent, StrategySelectionDecision } from "../evolution/mutationEngine.js";

export type AgentGraphState = {
  sessionId: string;
  goal: string;
  runContext?: {
    executionCwd?: string;
    fixtureWorkspace?: string;
    requestedRunMode?: string;
    fixtureMode?: boolean;
    livePatch?: boolean;
    liveAdvisory?: boolean;
    liveVision?: boolean;
    testCommand?: string;
    repairOnFail?: boolean;
    approveRepair?: boolean;
    fixtureFailingPatch?: boolean;
  };
  conversationTarget?: ConversationTarget;
  routing: RoutingPlan;
  access: AccessPolicy;
  events: TomorrowEdgeEvent[];
  eventArtifacts: EventArtifact[];
  providerViews: ProviderView[];
  evidencePackets: EvidencePacket[];
  agents: AgentRunState[];
  capabilityRoute?: CapabilityRoute;
  visualSpec?: StructuredVisualSpec;
  plan?: Plan;
  contextSelection?: ContextSelection;
  candidates: PatchCandidate[];
  repairCandidates: PatchCandidate[];
  debateRounds: DebateRound[];
  debateSession?: DebateSession;
  modelNotes: ModelNote[];
  usageSummary: ModelUsageSummary;
  workflowKind?: WorkflowKind;
  taskGovernance?: TaskGovernanceDecision;
  roleGraph?: RoleGraph;
  roleGraphExecution?: RoleGraphExecutionState;
  scenarioProfile?: ScenarioProfile;
  objectiveContract?: ObjectiveContractV1;
  contractVerification?: ContractVerificationResult;
  retrievedObjectiveTraces?: ObjectiveTraceV1[];
  orchestrationPolicy?: OrchestrationPolicyGenome;
  chiefAgent?: ChiefAgentProfile;
  chiefDecision?: ChiefAgentDecision;
  council?: CouncilSession;
  delegatedTaskResults?: DelegatedTaskResult[];
  strategyGenome?: StrategyGenome;
  strategyMutations?: StrategyMutationEvent[];
  strategySelection?: StrategySelectionDecision;
  finalChiefReview?: FinalChiefReview;
  toolSkillRoutes?: ToolSkillRouteDecision[];
  objectiveTrace?: ObjectiveTraceV1;
  workflowBlockedReason?: string;
  failureMemory?: FailureMemoryInfluenceState;
  budgetRuntime: BudgetRuntimeState;
  budgetStatus?: ModelBudgetStatus;
  budgetStatuses: ModelBudgetStatus[];
  review?: ReviewReport;
  judge?: JudgeDecision;
  changedFiles: string[];
  runResults: RunResult[];
  approvals: {
    patchApproved: boolean;
    shellApproved: boolean;
    repairApproved: boolean;
  };
  finalSummary?: FinalSummary;
  traceCompleteness?: TraceCompleteness;
};
