import { describe, expect, it } from "vitest";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { githubReportCommand } from "../../src/cli/commands/githubReport.js";
import { defaultConfig } from "../../src/config/defaultConfig.js";
import { runOfflineGraph } from "../../src/core/agentGraph/executor.js";
import { loadLatestSession, saveSession } from "../../src/core/memory/sessionMemory.js";
import { renderGithubPrReport } from "../../src/core/github/prReport.js";

describe("GitHub PR report", () => {
  it("renders a concise TomorrowEdge session report", async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), "tedge-github-report-"));
    try {
      const state = await runOfflineGraph(cwd, "fix failing test", defaultConfig, {
        provider: "fixture",
        approvePatch: true,
        approveShell: true
      });
      await saveSession(cwd, state);
      const output = await captureStdout(() => githubReportCommand(cwd, "latest", { dryRun: true }));

      expect(output).toContain("## TomorrowEdge Report");
      expect(output).toContain("Goal: fix failing test");
      expect(output).toContain("### Shell Checks");
      expect(output).toContain("Generated by TomorrowEdge");
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  }, 15_000);

  it("requires repo and PR when posting comments", async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), "tedge-github-report-"));
    try {
      const state = await runOfflineGraph(cwd, "report missing args", defaultConfig);
      await saveSession(cwd, state);

      await expect(githubReportCommand(cwd, "latest", { postComment: true })).rejects.toThrow("--repo");
      await expect(githubReportCommand(cwd, "latest", { postComment: true, repo: "owner/repo" })).rejects.toThrow("--pr");
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it("requires repo and PR or SHA when posting check runs", async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), "tedge-github-report-"));
    try {
      const state = await runOfflineGraph(cwd, "report missing check args", defaultConfig);
      await saveSession(cwd, state);

      await expect(githubReportCommand(cwd, "latest", { postCheck: true })).rejects.toThrow("--repo");
      await expect(githubReportCommand(cwd, "latest", { postCheck: true, repo: "owner/repo" })).rejects.toThrow("--sha");
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  });

  it("includes review draft material in report rendering", async () => {
    const cwd = await mkdtemp(path.join(os.tmpdir(), "tedge-github-report-"));
    try {
      const state = await runOfflineGraph(cwd, "fix failing test", defaultConfig, { provider: "fixture" });
      await saveSession(cwd, state);
      const report = renderGithubPrReport(await loadLatestSession(cwd));

      expect(report).toContain("### Review Drafts");
      expect(report).toContain("Correctness:");
    } finally {
      await rm(cwd, { recursive: true, force: true });
    }
  }, 15_000);
});

async function captureStdout(fn: () => Promise<void>): Promise<string> {
  const originalWrite = process.stdout.write.bind(process.stdout);
  let output = "";
  process.stdout.write = ((chunk: string | Uint8Array) => {
    output += String(chunk);
    return true;
  }) as typeof process.stdout.write;
  try {
    await fn();
  } finally {
    process.stdout.write = originalWrite;
  }
  return output;
}
